# https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md

insecure-entitlements = [ "security.insecure", "network.host" ]

[registry."dockerregistry:5000"]
  http = true
  insecure = true

[registry."192.168.68.70:5000"]
  http = true
  insecure = true

[worker.oci]
  platforms = [ "linux/amd64" ]